FROM ubuntu

# Copy the script to start Nginx and run tests
COPY start_services_and_tests.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/start_services_and_tests.sh

# Set up the ENTRYPOINT to run your start script
ENTRYPOINT ["/usr/local/bin/start_services_and_tests.sh"]
